name: CI/CD React

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    name: Build & Deploy React.js App
    runs-on: ubuntu-latest
    environment: webcup2025

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm install

      - name: Build React.js app
        run: npm run build

      - name: Package output
        run: |
          mkdir -p deploy_package
          cp -r dist/* deploy_package/

      - name: Copy to remote server via SCP
        uses: graygorssgarten/github-scp@release
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.SSH_PORT }}
          local: deploy_package
          remote: ${{ secrets.SSH_TARGET_PATH }}
